# ansible-galaxy role init httpd -> to create a role
---
- name: install httpd 
  hosts: localhost
  become: yes
  vars:
   web_pkg: httpd
   web_service: httpd
   web_default_file: /var/www/html
  tasks:
   - name: install httpd
     ansible.builtin.dnf:
      name: "{{web_pkg}}"
      state: present
   - name: start and enbale httpd
     ansible.builtin.systemd_service:
      name: "{{web_service}}"
      state: started
      enabled: true
   - name: deploy index.html file 
     ansible.builtin.copy:
      src: index.html
      dest: "{{web_default_file}}/index.html"
     