---
- name: Install and configure httpd
  hosts: localhost
  become: true

  tasks:
    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Deploy index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to my website</h1>

    