---
- name: installation of lemp stack
  hosts: localhost
  become: yes
  tasks:
   #install httpd, mariadb, php
   - name: install httpd
     ansible.builtin.dnf:
       name: httpd
       state: present

   - name: install maraidb
     ansible.builtin.dnf:
       name: mariadb105-server
       state: present

   - name: install php
     ansible.builtin.dnf:
       name: 
        - php
        - php-fpm
       state: absent
# start and enable httpd ,maraidb, php
   - name: start httpd
     ansible.builtin.systemd_service:
       name: nginx
       state: started
       enabled: true

   - name: start maraidb
     ansible.builtin.systemd_service:
       name: mariadb
       state: started
       enabled: true
  
   - name: start php
     ansible.builtin.systemd_service:
       name: php-fpm
       state: started
       enabled: true

  #deploy php page on apache
   - name: deploy php application
     ansible.builtin.copy:
       dest: /var/www/html/index.php
       content: |
        <?php
        phpinfo();
        ?> 
      