---
- name: installation of lemp with variable
  hosts: localhost
  become: yes
#define variable
  vars:
   web_pkg: nginx
   db_pkg: mariadb105-server
   php_pkgs: 
     - php
     - php-fpm
   
   web_service: nginx
   db_service: mariadb
   php_service: php-fpm
   php_index_file: /usr/share/nginx/html/index.php

  tasks:
    - name: install webserver
      ansible.builtin.dnf:
       name: "{{ web_pkg }}" #use variable
       state: present
    - name: install dbserver
      ansible.builtin.dnf:
       name: "{{ db_pkg }}"
       state: present

    - name: install php
      ansible.builtin.dnf:
       name: "{{ php_pkgs }}"
       state: present
    
    - name: start webserver
      ansible.builtin.systemd_service:
        name: "{{ web_service }}"
        state: started
        enabled: true 

    - name: start db-server
      ansible.builtin.systemd_service:
        name: "{{ db_service }}"
        state: started
        enabled: true

    - name: start php
      ansible.builtin.systemd_service:
        name: "{{ php_service }}"
        state: started
        enabled: true

    - name: deploy page
      ansible.builtin.copy:
        dest: "{{ php_index_file }}"
        content: |
         <?php
         phpinfo();
         ?>

      
      

      