---
- name: Deploy nginx app with handler (using blockinfile)
  hosts: webserver
  become: yes

  vars:
    web_pkg: nginx
    web_service: nginx
    web_root: /usr/share/nginx/html
    nginx_custom_conf: /etc/nginx/conf.d/custom.conf

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: "{{ web_pkg }}"
        state: present

    - name: ensure nginx running
      ansible.builtin.systemd_service:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: add custom nginx server block
      ansible.builtin.blockinfile:
        path: "{{ nginx_custom_conf }}"
        create: yes
        block: |
          server {
              listen 81;
              root {{ web_root }};
              index index.html;
          }
      notify: restart nginx

    - name: deploy html page
      ansible.builtin.copy:
        dest: "{{ web_root }}/index.html"
        content: "<h1>Hello from Ansible Nginx on {{ inventory_hostname }}</h1>"

  handlers:
    - name: restart nginx
      ansible.builtin.systemd_service:
        name: "{{ web_service }}"
        state: restarted
